---
#-------------------------------
# General Site Settings

title: Portfolio
logo:
author: themefisher
description: Laura Molina's Portfolio
email: ls.molina@hotmail.com
phone: 514-924-9862
address: Montreal, QC.
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  # - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title:  <br> Laura Molina <br> Comp Sci Student

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/laura-molina-3a85bb301" }
  - { icon: "ti-email", link: "mailto:ls.molina@hotmail.com" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: "Hello! My name is Laura Molina and I am 3rd year Computer Science student at John Abbott college. I know many current technologies such as C#, Python, and SQL. I am someone who is always in a good mood and I bring a positive attitude to every environment I am in."

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Web Programming, color: "#fdb157", value: "85%" }
  - { name: Databases, color: "#9473e6", value: "80%" }
  - { name: App Developement, color: "#bdecf6", value: "75%" }
  - { name: Networking and Security, color: "#ffbcaa", value: "65%" }

#-------------------------------
# Exprerience Section

# experience-title: Experience
# experience:
#   - {
#       name: Cashier,
#       icon: "icon-1.png",
#       date: "Summer 2020 & Summer 2021",
#       organization: "Le Zebre Rouge",
#     }
#   - {
#       name: Hostess & Server,
#       icon: "icon-2.png",
#       date: "May 2022 - May 2023",
#       organization: "Boston Pizza Vaudreuil",
#     }
#   - {
#       name: Food Service Worker,
#       icon: "icon-3.png",
#       date: "Jan 2024 - Sep 2024",
#       organization: "Marche Italanni",
#     }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Music Program - D.E.S,
      date: "2022",
      organization: "Ecole secondaire de la Cite des Jeunes",
    }
  - {
      name: D.E.C,
      date: "Expected 2025",
      organization: "John Abbott College",
    }
  # - {
  #     name: Higher Secondary Certificat,
  #     date: "2000",
  #     organization: "Cardiff School",
  #   }
  # - {
  #     name: Secondary School Certificate,
  #     date: "1998",
  #     organization: "Cardiff School",
  #   }

#-------------------------------
# Services Section

services-title: Hackathons & Clubs 
services:
  - {
      name: Programming Club,
      icon: ti-palette,
      description: "Fall 2023 - Participated in weekly mettings of the programming club at John Abbott",
      active: ,# Add true to select section
    }
  - {
      name: Girls Who Code,
      icon: ti-vector,
      description: "March 2024 - Participated in the Girls Who Code hackathon of McGill University. Designed a quiz app in a team of 3.",
      active: true, # Add true to select section
    }
  - {
      name: NSEC,
      icon: ti-panel,
      description: "May 2024 - Participated in the 2024 NSEC with the John Abbott team.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/LauraaMolinaa/security-project"
    description: "AES Symmetric Key Encryption"

  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/PIII-Assignments-F23/piii-course-project-pattie-laura"
    description: "Fun Geography Quiz App!"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://github.com/LauraaMolinaa/TheDeveloppers-HomeCalendar"
    description: "Calendar App"

  - image: "assets/images/portfolio/item-4.png"
    url: "https://github.com/LauraaMolinaa/Moodify"
    description: "Health and Wellness App."

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/LauraaMolinaa/security-project"
    description: "AES Symmetric Key Encryption"

  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/PIII-Assignments-F23/piii-course-project-pattie-laura"
    description: "Fun Geography Quiz App!"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://github.com/LauraaMolinaa/TheDeveloppers-HomeCalendar"
    description: "Calendar App"

  - image: "assets/images/portfolio/item-4.png"
    url: "https://github.com/LauraaMolinaa/Moodify"
    description: "Health and Wellness App"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: ls.molina@hotmail.com
